/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_reactnative_modules_update_DownloadTask */

#ifndef _Included_cn_reactnative_modules_update_DownloadTask
#define _Included_cn_reactnative_modules_update_DownloadTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_reactnative_modules_update_DownloadTask
 * Method:    bsdiffPatch
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_reactnative_modules_update_DownloadTask_bsdiffPatch
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
